name: Required format for main (lint)

on:
  push:
    branches:
      - main

jobs:
  sql-check:
    runs-on: ubuntu-latest

    steps:
        - name: Check out the repository
          uses: actions/checkout@v4
  
        - name: Set up Python
          uses: actions/setup-python@v4
          with:
            python-version: '3.10'
  
        - name: Install dependencies
          run: |
            python -m pip install --upgrade pip
            pip install sqlfluff
  
        - name: Run sqlfluff Script
          run: sqlfluff lint src/sql/ --dialect bigquery